<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="123" started-at="2020-07-13T14:17:37 EDT" finished-at="2020-07-13T14:17:37 EDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="123" started-at="2020-07-13T14:17:37 EDT" finished-at="2020-07-13T14:17:37 EDT">
      <class name="testclasses.TestNGDependentTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testclasses.TestNGDependentTests@3b0143d3]" name="setUp" is-config="true" duration-ms="13" started-at="2020-07-13T14:17:37 EDT" finished-at="2020-07-13T14:17:37 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testMethod2()[pri:0, instance:testclasses.TestNGDependentTests@3b0143d3]" name="testMethod2" duration-ms="15" started-at="2020-07-13T14:17:37 EDT" finished-at="2020-07-13T14:17:37 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [3]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [3]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at testclasses.TestNGDependentTests.testMethod2(TestNGDependentTests.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
        <test-method status="PASS" signature="testMethod4()[pri:0, instance:testclasses.TestNGDependentTests@3b0143d3]" name="testMethod4" duration-ms="3" started-at="2020-07-13T14:17:37 EDT" finished-at="2020-07-13T14:17:37 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod4 -->
        <test-method status="PASS" signature="testMethod1()[pri:0, instance:testclasses.TestNGDependentTests@3b0143d3]" name="testMethod1" duration-ms="2" started-at="2020-07-13T14:17:37 EDT" depends-on-methods="testclasses.TestNGDependentTests.testMethod2" finished-at="2020-07-13T14:17:37 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method status="PASS" signature="testMethod3()[pri:0, instance:testclasses.TestNGDependentTests@3b0143d3]" name="testMethod3" duration-ms="2" started-at="2020-07-13T14:17:37 EDT" depends-on-methods="testclasses.TestNGDependentTests.testMethod1" finished-at="2020-07-13T14:17:37 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod3 -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:testclasses.TestNGDependentTests@3b0143d3]" name="cleanUp" is-config="true" duration-ms="1" started-at="2020-07-13T14:17:37 EDT" finished-at="2020-07-13T14:17:37 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- testclasses.TestNGDependentTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
